name: Build for Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Build source
      shell: cmd
      run: |
        cd build/windows/
        build.bat

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: empty-pkcs11-windows
        path: build/windows/empty-pkcs11-*.dll
